version: "3.8"
services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  client:
    build:
      context: ./client
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always

